### ISSUE TITLE
Transaction note too long when installing package on large site

### ISSUE THREAD

**Issue by jone** [4teamwork/collective.lastmodifier#5]
When collective.lastmodifier is installed on a large site this happens:
- profile is installed, hook is triggered
- hook adds and reindexes index
- index accesses schemaextender (field.get)
- getter detects that there is no value, sets default value
- because the default value is used, archetypes adds a info to the transaction note
- when this happens a lot, the transaction note gets too large
- the transaction cannot be committed at the end

/cc @mbaechtold

**Comment by mbaechtold** [comment]
@jone: is this still an issue or has it been solved with https://github.com/4teamwork/ftw.upgrade/commit/44efe457020f69ce00dff613252a090c291497c7 ?

**Comment by jone** [comment]
This is solved, since the Archetypes transaction notes are only added when there is enough space left. The problem was in ``ftw.upgrade`` and is fixed with the above mentioned commit: ``ftw.upgrade`` now has the same behavior.
It was edge case which only occured when only little space was left..
